id: env_0143g1w3cB9SZMVHUXNz4DbJ
name: workshop-pptx
config:
  type: cloud
  networking:
    type: unrestricted
  packages:
    apt:
      - libreoffice
      - poppler-utils
    pip:
      - python-pptx
      # - matplotlib